# Generated by Django 5.1.1 on 2024-10-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("road_name", models.CharField(max_length=255)),
                (
                    "apartment_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("flat_number", models.CharField(blank=True, max_length=50, null=True)),
                ("post_code", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20)),
                ("item_name", models.CharField(max_length=255)),
                ("size_name", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("salad_toppings", models.TextField(blank=True, null=True)),
                ("sauce_toppings", models.TextField(blank=True, null=True)),
                ("quantity", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "orders",
            },
        ),
    ]
