# Generated by Django 5.1.1 on 2024-10-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_remove_order_item_name_remove_order_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
