# Generated by Django 5.1.1 on 2024-09-19 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('salad_toppings', models.CharField(blank=True, max_length=200, null=True)),
                ('sauce_toppings', models.CharField(blank=True, max_length=200, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.items')),
                ('sizes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.sizes')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='orders.cartitem')),
            ],
        ),
    ]
