# Generated by Django 5.1.1 on 2024-10-01 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_cartitem_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="item",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="sizes",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
