# Generated by Django 5.1.1 on 2024-10-20 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_cartitem_item_remove_cartitem_sizes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemsizes",
            options={},
        ),
    ]
